### ISSUE TITLE
Error if(player.object != -1) {

### ISSUE THREAD

**Issue by hikari-no-yume** [Gang-Garrison-2/Gang-Garrison-2#104]
Error usually happens on the rj_technic map (sometimes on others). The error constantly pops up just as you play (I usually play as the demo man)   GG2 version 2.5  and I dont remember what server it was sorry. again the error is 

http://imgur.com/oidGMor

In script ClientBeginStep:
Error in code at line 229:

```
        if(player.object != -1) {
                     ^
```

at position 24: Unknown variable object

Launchpad Details: [#LP1168204](https://bugs.launchpad.net/bugs/1168204) bazoom - 2013-04-12 02:58:38 +0100

**Comment by arctic5** [comment]
duplicate of this
https://github.com/Gang-Garrison-2/Gang-Garrison-2/issues/142

**Comment by Medo42** [comment]
Not clear to me that this is a duplicate, only the symptoms are similar

**Comment by Medo42** [comment]
In fact, I'm pretty sure it's not a dupe.

**Comment by harmjanhaisma** [comment]
its because the player object was missing at the point when this happend.

**Comment by Medo42** [comment]
Closing some old bug reports where the cause is unclear and which might be outdated
