### ISSUE TITLE
Rifleman scope state not synced on full/quick update

### ISSUE THREAD

**Issue by hikari-no-yume** [Gang-Garrison-2/Gang-Garrison-2#106]
Information:
Rifleman's scope state (scoped in vs unscoped) is synced with a toggler event, demanded by the client playing Rifleman of the server, and the server replicates it to all clients.
Bug:
If a client joins a server where a sniper is scoped in, the Rifleman appears to be unscoped. When the Rifleman unscopes on the server side, they scope in on the client side.
Replication:
Create a server, join a team, select sniper, and scope in.
Create a client, connect to the server, and observe that the state is different between the client and server.

Launchpad Details: [#LP1184042](https://bugs.launchpad.net/bugs/1184042) Wareya - 2013-05-25 01:02:51 +0100

**Comment by Medo42** [comment]
This was fixed by wareya in https://github.com/Gang-Garrison-2/Gang-Garrison-2/commit/4ef86640bc3c43c1c0868bb116a8406f7771f14d#diff-3b5372e1be692e3d310c579778c37f89R57
