### ISSUE TITLE
Round End Sentry Bolt Bug

### ISSUE THREAD

**Issue by hikari-no-yume** [Gang-Garrison-2/Gang-Garrison-2#107]
ERROR in
action number 1
of Begin Step Event
for object Client:

In script ClientBeginStep:
In script buildSentry:
Error in code at line 22:

player.object.nutsNBolts -= 100;
   ^
at position 2: Unknown variable nutsNBolts

Did a player destroy his sentry when the round ended and the other picked it up?

EDIT: The error appeared at the next map and i crashed.

Launchpad Details: [#LP1196612](https://bugs.launchpad.net/bugs/1196612) SecretMan - 2013-07-01 17:48:42 +0100

**Comment by Medo42** [comment]
Closing because it's old and we'd have a hard time figuring it out.
