### ISSUE TITLE
when you die or kill the enemy teleport to a location near where you killed

### ISSUE THREAD

**Issue by TazeTSchnitzel** [Gang-Garrison-2/Gang-Garrison-2#114]
If you kill anyone in gang garrison 2 they teleport to a location near where you killed and if anyone kill you you teleport to a locaton near you died but you teleport died

Launchpad Details: [#LP1293094](https://bugs.launchpad.net/bugs/1293094) Daniel Erdmann(Narudan) - 2014-03-16 11:48:50 +0000

**Comment by arctic5** [comment]
dont really get how much more info can you give? the body just straight up teleports when it dies for no reason whatsoever

**Comment by Medo42** [comment]
I just killed someone in GG2. Neither they nor their body teleported to a location near me. This contradicts the bug report, so I assume the reporter is talking about more specific circumstances that are not made explicit. In other words, I have `insufficient information` to reproduce the bug. If you know  why the OP experiences this problem and I don't, please share this insight.

**Comment by wareya** [comment]
It used to be that when you died the ragdoll would go inside of the wallmask and then come out somewhere else due to rectification code. That doesn't happen anymore now that the ragdoll mask is (?) a single point.

**Comment by arctic5** [comment]
so we can close this rite?

**Comment by TazeTSchnitzel** [comment]
Sounds like it's fixed then.
