### ISSUE TITLE
Control layout changes are not persistent

### ISSUE THREAD

**Issue by hikari-no-yume** [Gang-Garrison-2/Gang-Garrison-2#116]
Changing keyboard layout in the Options menu does not get stored into an ini file, and hence all changes disappear.

A user came on IRC with this problem, and I can confirm it from own testing as well.
The ControlsController should theoretically do this on destroy, I think this is again a problem of destruction not working properly in room change.

As a temporary hotfix I just told people to use this plugin and to insert their keybindings in it. Not a good permanent solution though:

object_event_add(SplashController, ev_create, 0, '
    global.jump = ord("W");
    global.down = ord("S");
    global.left = ord("A");
    global.right = ord("D");
    global.attack = MOUSE_LEFT;
    global.special = MOUSE_RIGHT;
    global.taunt = ord("F");
    global.chat1 = ord("Z");
    global.chat2 = ord("X");
    global.chat3 = ord("C");
    global.medic = ord("E");
    global.drop = ord("B");
    global.changeTeam = ord("N");
    global.changeClass = ord("M");
    global.showScores = vk_shift;
');

Version: 2.7.2

Launchpad Details: [#LP1301596](https://bugs.launchpad.net/bugs/1301596) Orpheon - 2014-04-02 21:34:39 +0100

**Comment by Medo42** [comment]
Probably outdated. Just checked and it works fine for me.
