### ISSUE TITLE
Overweight glitching through spawn

### ISSUE THREAD

**Issue by TazeTSchnitzel** [Gang-Garrison-2/Gang-Garrison-2#120]
Basically, I saw an overweight when I was playing GG2 on United States of Survillience, he walked up to my base and started freaking out...
He was shooting the spawn doors and jerking like a fish. 
I didnt care, he was probably gonna get stabbed  but he glitched through the spawn doors and camped us all.

Thank god he got backstabbed 1 minute later...

His name was 'Player13'

Hopefully he didnt change his name!  D:

Launchpad Details: [#LP1304018](https://bugs.launchpad.net/bugs/1304018) BooBasher5000/Cloudy - 2014-04-07 21:35:19 +0100

**Comment by arctic5** [comment]
one of those bugs with spawndoors that was fixed with the new physics a few updates ago

**Comment by TazeTSchnitzel** [comment]
do we actually know if this is fixed

**Comment by wareya** [comment]
99% certainty

**Comment by wareya** [comment]
either way it's a very bad report and we don't have a way of  getting more information from the original reporter

**Comment by TazeTSchnitzel** [comment]
Fair point. If it's still an issue (quite possibly, GG2 collision is a mess) a new issue can be made.
