### ISSUE TITLE
Allow GG2 to run without internet

### ISSUE THREAD

**Issue by TazeTSchnitzel** [Gang-Garrison-2/Gang-Garrison-2#122]
GG2 currently does several requests to the ganggarrison.com server for the devmessage, background image, update tracker, etc.
These block and crash the game if for some reason a connection cannot be made.

Could we add some more graceful failing, or at least an option to "stay offline" for those running gg2 in schools or other protected environments that don't allow random applications to do random online requests?

Putting this in Bug Reports because ajf wanted it here, if this is the wrong place I could also post this in Feature Requests.

Launchpad Details: [#LP1363993](https://bugs.launchpad.net/bugs/1363993) Orpheon - 2014-09-01 13:43:33 +0100

**Comment by Derpduck** [comment]
I fixed this in DSM ages ago by putting an alarm in DevMessageChecker that destroys the instance after a reasonable amount of time. Do that.

**Comment by TazeTSchnitzel** [comment]
There shouldn't be a need to, given Faucet HTTP *should* be non-blocking given it uses Faucet Networking. But if it can be confirmed to still be an issue, I could look into.

**Comment by TazeTSchnitzel** [comment]
This definitely was an issue at some point, but I tested this now and it's fixed.
