### ISSUE TITLE
Floaty blood

### ISSUE THREAD

**Issue by lorgan3** [Gang-Garrison-2/Gang-Garrison-2#126]
It's probably a "feature" but it looks really weird to me.
![2014-09-06 11-38-08 us-w snowman s 24-7 ctf_rsm](https://cloud.githubusercontent.com/assets/1833617/4174804/dc626c76-35a9-11e4-952f-5a2af98554d5.png)

**Comment by TazeTSchnitzel** [comment]
So, we just need rounding?

**Comment by Medo42** [comment]
I think rounding is the wrong approach. Just replace `speed -=
0.1*global.delta_factor;` with `speed = max(0,
speed-0.1*global.delta_factor);`

Andrea Faulds <notifications@github.com> schrieb am Mo., 09.02.2015, 0:38:

**Comment by TazeTSchnitzel** [comment]
Ah! Yes, that should work.

**Comment by wareya** [comment]
fix committed at https://github.com/wareya/Gang-Garrison-2/commit/8572cb69403f943316f50239382c6e7e89f18958

**Comment by wareya** [comment]
fix commited at https://github.com/wareya/Gang-Garrison-2/commit/671df6d325ca336066a4b18de917dd0f58e20de3

**Comment by wareya** [comment]
Make that https://github.com/wareya/Gang-Garrison-2/commit/62896ebe0fabd8567d7a2b749536241ba485d30b

**Comment by TazeTSchnitzel** [comment]
Committed *where*? "Fix committed" means commits to master, that's just in your repo...

**Comment by wareya** [comment]
If that were true it would mean the fix is commited to Gang-Garrison-2/master :)

**Comment by arctic5** [comment]
2.8 pls get wit the program

**Comment by TazeTSchnitzel** [comment]
:p

**Comment by TazeTSchnitzel** [comment]
Fixed by wareya: https://github.com/Medo42/Gang-Garrison-2/pull/258
