### ISSUE TITLE
arena error

### ISSUE THREAD

**Issue by arctic5** [Gang-Garrison-2/Gang-Garrison-2#136]
ERROR in
action number 1
of  Step Event
for object ControlPoint:

Error in code at line 198:
           capTime = baseCapTime * livereds/reds;
                                            ^
at position 43: Division by 0.

**Comment by Medo42** [comment]
Please reference the commit which fixes each bug, or reference the ids of
fixed bugs in the commit message (e.g. "closes #136") so that github can
cross-reference them automatically once we pull the commits into the group
repo.
Am 08.01.2015 05:30 schrieb "jason" <notifications@github.com>:

**Comment by TazeTSchnitzel** [comment]
What MedO said.

GitHub seems to recognise "fixes #12345" but not "fixes bug #12345", so bear that in mind.
