### ISSUE TITLE
Possible performance improvements for GGON

### ISSUE THREAD

**Issue by TazeTSchnitzel** [Gang-Garrison-2/Gang-Garrison-2#137]
This is mostly here as a note to myself, but:

* We should not successively truncate the input text when tokenising. Instead, store the index into the string in some variable, and increment that. This would reduce string allocations and, especially for long strings, remove this exponential time element (each iteration we copy, which means each iteration we do an O(n) string copy)
* The token types could be numerical constants. This is probably ever-so-slightly faster. Note that [the PHP implementation](https://github.com/TazeTSchnitzel/GGON/blob/master/src/Parser.php) already uses constants, they're just defined to their string values.

Plus, not strictly performance-related, but:

* We could actually add list syntax. This would make GGON nicer to read and write. Of course, it would still decode to and encode from a map in the same format list_to_map and map_to_list produce now, but the syntax would be nicer. Now the items would be sorted in the list in their actual order (rather than lexicographically), it'd be less verbose (no explicit IDs), and it'd be possible to edit by hand (currently you'd have to update every single ID after an insertion point, and the length). This adds some overhead when encoding, as you need to check that the map is list-like, but there's no reason that *encoding* has to be fast, only decoding. It might be possible to add a `real` key which tells us that a map is a list, to avoid this overhead. I'm not sure if we completely ignore real keys just now, though. **This would need to be added before GGON is included in a released version of GG2, to avoid incompatibilities.**

**Comment by TazeTSchnitzel** [comment]
Oh yeah, this pull request fixes this: https://github.com/Medo42/Gang-Garrison-2/pull/246

It doesn't do the numerical constants thing though, it does something *better*: it uses prefixes instead.

**Comment by arctic5** [comment]
it didnt close automatically probably because you referenced the wrong one
