### ISSUE TITLE
Meow: if u stand on a dropdown u can walk through wallmasks

### ISSUE THREAD

**Issue by arctic5** [Gang-Garrison-2/Gang-Garrison-2#138]
![vmptukf 1](https://cloud.githubusercontent.com/assets/4969181/4711689/dc49087a-58be-11e4-8bdf-77ae6c7635c4.gif)

**Comment by wareya** [comment]
I still don't know why this is happening.

**Comment by wareya** [comment]
I still haven't figured this out.

**Comment by arctic5** [comment]
RIP
