### ISSUE TITLE
ajf pls

### ISSUE THREAD

**Issue by lorgan3** [Gang-Garrison-2/Gang-Garrison-2#141]
ERROR in
action number 1
of  Step Event
for object PluginEnvironment:

In script http_step:
In script __http_client_step:
In script __http_resolve_url:
Error in code at line 92:
   
        query = string_copy(refUrl, queryPos + 1, string_length(relUrl) - queryPos);
                                                                   ^
at position 66: Unknown variable relUrl

^relUrl should be refUrl

**Comment by arctic5** [comment]
4:39 AM - arctismo: ok l mme just assign ajf
4:39 AM - arctismo: MFW
4:39 AM - arctismo: clicked the wrong person
4:39 AM - arctismo: (me)

**Comment by TazeTSchnitzel** [comment]
This is a bug in Faucet HTTP, please open an issue there: https://github.com/TazeTSchnitzel/Faucet-HTTP-Extension

**Comment by TazeTSchnitzel** [comment]
Closing issue since it's a Faucet HTTP issue: https://github.com/TazeTSchnitzel/Faucet-HTTP-Extension/issues/1

I'll fix it there and update GG2's Faucet HTTP version.

**Comment by TazeTSchnitzel** [comment]
Fixed in GG2: https://github.com/Medo42/Gang-Garrison-2/pull/252

**Comment by arctic5** [comment]
i swear you 2 make way too many new tags for bugs
