### ISSUE TITLE
SpriteObject and MovingPlatform change movement speed when you toggle 60FPS in-game

### ISSUE THREAD

**Issue by Medo42** [Gang-Garrison-2/Gang-Garrison-2#144]
See https://github.com/Medo42/Gang-Garrison-2/pull/247#discussion-diff-26447772

Should be fairly easy to fix. I didn't actually test, just read the code, so consider this unconfirmed.

**Comment by lorgan3** [comment]
It's been a while since I wrote this stuff or even looked at the source code, but didn't @wareya make it so that the fps changes only work after a mapchange?

**Comment by wareya** [comment]
Yes, because of uses like this and alarms. If it's possible to change FPS while running a map, that itself would be the bug.

**Comment by Medo42** [comment]
That's why I said consider it unconfirmed :)
