### ISSUE TITLE
No MPL.txt in the repo

### ISSUE THREAD

**Issue by TazeTSchnitzel** [Gang-Garrison-2/Gang-Garrison-2#146]
Fairly self-explanatory. GG2 is MPL-licensed, but there's no copy of the license itself in the repository, unfortunately.

**Comment by Medo42** [comment]
We can add one, but I don't think it's actually required.

Andrea Faulds <notifications@github.com> schrieb am Mo., 23.03.2015, 13:54:

Fairly self-explanatory. GG2 is MPL-licensed, but there's no copy of the

**Comment by TazeTSchnitzel** [comment]
It's not required, no, but it's a little weird to say "If a copy of the MPL was not distributed with this file, You can obtain one" if we *never* distribute a copy.

**Comment by TazeTSchnitzel** [comment]
Also, you must have fudged your email reply, because it included the quote. :p

**Comment by cspotcode** [comment]
I wonder if Github doesn't understand the German reply header?

**Comment by TazeTSchnitzel** [comment]
@cspotcode I think it looks for a marker and you have to reply above that line.

**Comment by Medo42** [comment]
<zen>Everything has been said.</zen>
