### ISSUE TITLE
blue rocket man when reloading has red arms and the red rocketman reloading animation doesn't finish

### ISSUE THREAD

**Issue by arctic5** [Gang-Garrison-2/Gang-Garrison-2#147]
blue rocket man when reloading has red arms and the red rocketman reloading animation doesn't finish

update:
12:26 PM - smooth jazz: blue medic arms turn red when reloading too
12:26 PM - smooth jazz: and red spy reload animations doesnt work only bullets come out

**Comment by lorgan3** [comment]
I think i tried fixing this before but couldn't figure out why

**Comment by arctic5** [comment]
TRY HARDER

**Comment by lorgan3** [comment]
No u

**Comment by Medo42** [comment]
Could be please have something resembling a professional attitude in here? This is like supervising a Kindergarten class.

**Comment by arctic5** [comment]
Well, I'm not the best at naming things

**Comment by arctic5** [comment]
update:
12:26 PM - smooth jazz: blue medic arms turn red when reloading too
12:26 PM - smooth jazz: and red spy reload animations doesnt work only bullets come out

**Comment by lorgan3** [comment]
Spy is a lie!
![reload](https://cloud.githubusercontent.com/assets/1833617/6996136/2783ea7e-db75-11e4-89a3-315adbfd08b9.gif)

Medic is probably the same issue as rocketman and it probably happens for other classes too, but you don't notice because their weapons don't have teamcolors.

**Comment by lorgan3** [comment]
Ok I think i squashed this bug now.
https://github.com/Medo42/Gang-Garrison-2/pull/261

**Comment by arctic5** [comment]
cool now we just need to wait for someone to stick a stupid label on it

**Comment by arctic5** [comment]
git the fuk outta here wit your stupid labels

**Comment by Medo42** [comment]
@lorgan3 it's not correct to close this before it's pulled into master (or arguably even before the fix is in a release)

**Comment by Medo42** [comment]
I guess we will have to figure out at some point how to use this system well :P

**Comment by arctic5** [comment]
why did you remove a label that actually should be there
