### ISSUE TITLE
Pyro Windows 8.1 Issues?

### ISSUE THREAD

**Issue by JerseyJackal** [Gang-Garrison-2/Gang-Garrison-2#153]
http://i.imgur.com/J6q4Ytw.png

Looks like it's directmusic's fault in this case. A fluke or could the issues still be unresolved?

**Comment by Medo42** [comment]
Unfortunately I can't test this myself because I still run Windows 7, but could you try whether this happens reproducably when two pyros are firing at the same time?

**Comment by arctic5** [comment]
id say this is a crash because too many sounds are playing for the sound_stop fix to catch it fast enough

**Comment by wareya** [comment]
sound_stop is supposed to stop the sounds at the next internal API step

**Comment by Medo42** [comment]
This is just from a quick skim, but we seem to do the sound_stop only for one-shot sounds (playsound script), not for looped sounds (loopsoundstart script). However, calling sound_loop twice on the same sound might be a no-op anyway. I don't have time to test this right now or dig further.

**Comment by Medo42** [comment]
The best solution for this would be to finally adopt one of the sound extensions we have available now.

**Comment by Medo42** [comment]
Duplicate of #11
