### ISSUE TITLE
Credits run twice as fast in 60fps

### ISSUE THREAD

**Issue by Derpduck** [Gang-Garrison-2/Gang-Garrison-2#16]

**Comment by Medo42** [comment]
I just tested this and it seems to be fixed in this commit from 23 April 2014: https://github.com/Medo42/Gang-Garrison-2/commit/82f0f6e9c448454f00614b0bbd362dc31a0be80f

This was after this issue was created, but before wareya self-assigned it. Eeh, whatever, it's fixed.

**Comment by wareya** [comment]
I don't actually remember self-assigning this.
