### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by DanielBrumTorres** [Gang-Garrison-2/Gang-Garrison-2#161]
The game crashes on startup, please help!

**Comment by wareya** [comment]
Need more information.

**Comment by DanielBrumTorres** [comment]
I click on the icon to play, then it shows that Steam screen when you're starting up a game, then nothing happens, the game dosen't start up.

**Comment by wareya** [comment]
What operating system are you using? What is your graphics card? What is your GPU? What is your CPU? What antivirus/antimalware software do you run?

**Comment by DanielBrumTorres** [comment]
I'm using windows XP, my computer can run Skyrim, and my antivirus is Avira.

**Comment by wareya** [comment]
What directory are you running the game from?

**Comment by DanielBrumTorres** [comment]
I'm running it from my documents.

**Comment by wareya** [comment]
Sometimes downloads become corrupt. Game Maker games are encrypted, which causes corruption to break the entire game data. Have you tried redownloading the game?

**Comment by DanielBrumTorres** [comment]
No, but i will try it now, thanks.

**Comment by DanielBrumTorres** [comment]
Tried it from the same directory, and then from the C disk, both did not work.

**Comment by TazeTSchnitzel** [comment]
You are not giving us sufficient information to deal with your problem. Please provide more details about your computer than merely that it uses XP, for example.

**Comment by TazeTSchnitzel** [comment]
If you are unable to do this, you may wish to try magnetising your system32 with water.

**Comment by wareya** [comment]
Clarification: water system32 your water with magnets.

(Don't do this.)

**Comment by DanielBrumTorres** [comment]
Gah, i was just wanting to play this game, but it's taking too long, it's not worth it, but thanks for trying to help.

**Comment by TazeTSchnitzel** [comment]
If you gave us basic information we might have been able to help you.

**Comment by Medo42** [comment]
As the tag said, Figuring out what went wrong here would require more information / interactively testing things, and I don't think the OP is still interested enough for that.
