### ISSUE TITLE
Sniper OP pls nerf

### ISSUE THREAD

**Issue by TazeTSchnitzel** [Gang-Garrison-2/Gang-Garrison-2#162]
![](https://dl.dropboxusercontent.com/u/9120295/images/GG2F/plsnerf.gif)

Full proposal, by Sani (who also made image): http://www.ganggarrison.com/forums/index.php?topic=36737.0

**Comment by Medo42** [comment]
Nice gif :)
Generally the idea is good, but we'd need some visual indication that the range is limited.

**Comment by TazeTSchnitzel** [comment]
Yeah, it's an issue I've been wondering about.

**Comment by arctic5** [comment]
http://www.ganggarrison.com/forums/index.php?topic=36737.msg1262862#msg1262862

**Comment by arctic5** [comment]
http://www.ganggarrison.com/forums/index.php?topic=36737.msg1262862#msg1262862
i did some testing and there is no way to possibly see the end of your shot so it really feels unnecessary to have an indicator about things you cant see by normal means in the first place

**Comment by Medo42** [comment]
Merged in https://github.com/Medo42/Gang-Garrison-2/pull/291

**Comment by wareya** [comment]
Yayifications!
