### ISSUE TITLE
current arena score not synced on joining a server

### ISSUE THREAD

**Issue by Derpduck** [Gang-Garrison-2/Gang-Garrison-2#164]

**Comment by wareya** [comment]
Still apply?

**Comment by PrOF-kk** [comment]
This has been fixed in 42170de60585ba863ee74087c099c93dfe181c7a, see [lines 18-19](https://github.com/Gang-Garrison-2/Gang-Garrison-2/blob/master/Source/gg2/Objects/Overlays/Gamemodes/ArenaHUD.events/User%20Event%2012.xml#L18-L19)
