### ISSUE TITLE
Invisible bullets

### ISSUE THREAD

**Issue by TheRocketJumper** [Gang-Garrison-2/Gang-Garrison-2#166]
In some instances when booting up GG2 and joining a game, the shot bullets are invisible but the rockets, needles, blades, bubbles, flames, flares and mines are fine.

**Comment by arctic5** [comment]
probably lag/desync/mod issue has never happened to me

**Comment by wareya** [comment]
TRJ: PM me on the forum if this ever happens on a vanilla server and I'll reopen the issue.
