### ISSUE TITLE
scout not refreshing jumps on dropdown

### ISSUE THREAD

**Issue by Derpduck** [Gang-Garrison-2/Gang-Garrison-2#167]
http://puu.sh/lfHus/cbb8b0dc8f.gif
when you land on a dropdown, as shown in the gif, where i was mashing the jump button once i jumped after landing on the dropdown, you do not have your jumping reset, so you only have your 2nd jump left until you land again, where it is reset normally

**Comment by wareya** [comment]
thx

**Comment by wareya** [comment]
https://github.com/Medo42/Gang-Garrison-2/blob/master/Source/gg2/Objects/InGameElements/Character.events/Begin%20Step.xml#L69 deserves a rewrite

**Comment by wareya** [comment]
sorry wrong code

https://github.com/Medo42/Gang-Garrison-2/blob/master/Source/gg2/Objects/InGameElements/Character.events/Begin%20Step.xml#L254

Probably here
