### ISSUE TITLE
.exe deleted upon opening for no reason

### ISSUE THREAD

**Issue by Fagmag** [Gang-Garrison-2/Gang-Garrison-2#168]
Whenever i try to run (sometimes without even clicking on it) after decompressing the files, it says the .exe couldn't be found or that i don't have permission to open it, where it also gets erased without a trace.

Specs:

Windows 8.1
8gig RAM
Hewlett-Packard
Intel HD graphics

**Comment by wareya** [comment]
Do you use an antivirus or similar software? If so, what one?

**Comment by Fagmag** [comment]
Norton 360.

**Comment by Medo42** [comment]
Closing because it doesn't seem we can do anything to help here.
