### ISSUE TITLE
Auto-Balance still defies classlimits!

### ISSUE THREAD

**Issue by TheRocketJumper** [Gang-Garrison-2/Gang-Garrison-2#170]
Why was the old report closed when it clearly isn't fixed.

Screenshot taken 2016 April: i.imgur.com/MaG7zcu.png

**Comment by Medo42** [comment]
The old report was closed because we implemented a fix. The class limits are definitely checked now when someone is switched by the autobalancer. I'm not sure how the situation in this screenshot came about.
