### ISSUE TITLE
Having # in username causes the kill log to create a new line for deaths with no defined killer

### ISSUE THREAD

**Issue by ZaSpai** [Gang-Garrison-2/Gang-Garrison-2#171]
Pretty much an oversight since the rest display # properly

**Comment by ZaSpai** [comment]
Actually also includes the mini info bar when it says x player has been switched for team balance

**Comment by Medo42** [comment]
Should be easy enough to fix.

**Comment by Medo42** [comment]
I don't see it happening in the kill log. I did fix another name display issue before testing but it should be unrelated. How do I reproduce this?
http://ganggarrison.com/filehost/sharex/Gang%20Garrison%202_2016-05-16_13-12-07.png

**Comment by Medo42** [comment]
Did fix it for the autobalancer

**Comment by Medo42** [comment]
Never mind, found it.
