### ISSUE TITLE
Error on server when tdm or dm maps appear First in map rotation

### ISSUE THREAD

**Issue by Medo42** [Gang-Garrison-2/Gang-Garrison-2#174]
SevereHazard writes:

> "I found this error when I host a server and tdm, or dm maps appear First in map rotation."
> 
> ERROR in
> action number 1
> of Begin Step Event
> for object HUD:
> 
> Error in code at line 45:
>    if global.TimeLeftTillStart>0 and global.TimeLeftTillStart mod 30 = 0
>             ^
> at position 11: Unknown variable TimeLeftTillStart

**Comment by wareya** [comment]
This was confirmed to be a plugin bug on the forum.
