### ISSUE TITLE
We warn about VSync when hosting, yet we disable it anyway

### ISSUE THREAD

**Issue by hikari-no-yume** [Gang-Garrison-2/Gang-Garrison-2#175]
Host Options:

> Warning: VSync appears to be enabled. Hosting with VSync causes desync.

Engine Options:

> V Sync: On unless hosting

I'm guessing this is an oversight?

**Comment by wareya** [comment]
Yes. The second example was added afterwards.

**Comment by PrOF-kk** [comment]
Confirmed not outdated, surely GG2's fault:
![Image of bug](https://i.imgur.com/EjpsX1R.png)

**Comment by wareya** [comment]
Just so you know the "probably gg2's fault" is just an umbrella tag for things that are Almost Definitely not caused by GM or the OS, like behavioral problems like this.

**Comment by PrOF-kk** [comment]
Alright 👍 
At least we're sure it isn't outdated. I'll fix this right after pull #299 gets accepted/closed

**Comment by Medo42** [comment]
See 0b616c678e7fa63ab2a6cf28aab7135709d98f13
