### ISSUE TITLE
i accidentally avanti

### ISSUE THREAD

**Issue by TazeTSchnitzel** [Gang-Garrison-2/Gang-Garrison-2#176]
```
17:10 - Heim Rada: hey
17:11 - Heim Rada: remember when you modified gg2 to use internal map files?
17:11 - Heim Rada: you accidentally killed adctf avanti
```

https://github.com/Medo42/Gang-Garrison-2/commit/4946e10804a86192b67725767c40d450de72d494

oops

thanks @wareya for pointing this out

**Comment by Medo42** [comment]
Yay, something to fix for the Q4 release ;)
