### ISSUE TITLE
Error when hosting server for quite some time.

### ISSUE THREAD

**Issue by SHITFACE11** [Gang-Garrison-2/Gang-Garrison-2#178]
ERROR in
action number 1
of Trigger Event: <Deleted>
for object MovingPlatform:

Error in function real().

**Comment by Medo42** [comment]
When I am up for too long, I also have trouble figuring out what is real ;)

**Comment by Medo42** [comment]
This seems to be a mod issue, because vanilla GG2 does not use trigger events. Which mods are you using?

**Comment by SHITFACE11** [comment]
The regular gg2 client. So vanilla.  I think it might be the plugins I'm using? I don't see any problem with it tho.

**Comment by SHITFACE11** [comment]
Could explosivetaunt and chatlogging plugin might effect it.

**Comment by Medo42** [comment]
Unless this happened after you entered a command into the console, I don't think the plugins are causing it. GM is probably confused about the event context for some reason. I'd have to figure out when this happens (one idea would be room creation). This is all just to figure out where this error actually occurs so we can begin to find out what is actually going wrong...

**Comment by Medo42** [comment]
There are actually not that many places where real() is called. Could it be a defective map file? This seems the most likely cause right now (though really I haven't figured anything out :P)

**Comment by Medo42** [comment]
I can replicate the issue by triggering the error on purpose during map loading: http://www.ganggarrison.com/filehost/sharex/Gang%20Garrison%202_2016-12-25_22-45-59.png

**Comment by SHITFACE11** [comment]
So is it the error from map rotation or just the map file in general

**Comment by SHITFACE11** [comment]
K got it. I  found out the map that replicated that error. This issue is solved. Thx Medo.

**Comment by SHITFACE11** [comment]
now this appeared ERROR in
action number 1
of Draw Event
for object Character:

Error in function real().

**Comment by Medo42** [comment]
Another broken map?

**Comment by Medo42** [comment]
So as I understand it this was not GG2's fault but a broken map.
