### ISSUE TITLE
HAX!

### ISSUE THREAD

**Issue by NothingIsOkay1** [Gang-Garrison-2/Gang-Garrison-2#179]
There's a hacker on GG2, it has no name, (example = '' Flamethrower pootis '', there isnt the name of the one that got the kill, since its blank), his hack, is that he can see cloaked spies, if you see him on a server, go spy, and go to him, he will look at you and kill you.

**Comment by wareya** [comment]
Unfortunately, GG2 has no anticheat, and doesn't have ban tools built in because of the negative effect it would have on such a small community. You have to find a way to ask the server owner to use a modification to ban them.

**Comment by wareya** [comment]
Accidentally pressed the close button, sorry.

**Comment by NothingIsOkay1** [comment]
thanks for your response, its really bad to see that...

**Comment by Medo42** [comment]
We already have an issue for that (#60), so I'm closing this one as a duplicate.
