### ISSUE TITLE
Sniper scoping modifies jump height directly

### ISSUE THREAD

**Issue by wareya** [Gang-Garrison-2/Gang-Garrison-2#184]
https://github.com/Medo42/Gang-Garrison-2/blob/8b7717a5eab68a3ebc3b1d4810d282ae0d297033/Source/gg2/Scripts/toggleZoom.gml

**Comment by wareya** [comment]
This makes the rifleman jump shorter than he's supposed to.

https://github.com/Medo42/Gang-Garrison-2/blob/master/Source/gg2/Objects/InGameElements/Character.events/Create.xml#L24

**Comment by ZaSpai** [comment]
Would the zoomed jumpStrength also have to be adjusted for the first frame to match what zoomed jumping would have behaved like in old gg2?
