### ISSUE TITLE
"Wrong amount of players while deserializing state"

### ISSUE THREAD

**Issue by Kostia4381** [Gang-Garrison-2/Gang-Garrison-2#186]
Hello. I was playing some servers recently, I was getting the following:

> "Wrong amount of players while deserializing state"

After I clicked "OK", the game crashes with a fatal error:

> FATAL ERROR in
> action number 1
> of Create Event
> for object Character:
> 
> Attempted to get a sprite for unknown team ID: 2

I assume ID: 2 is unused, while -1 is spectator and 0 and 1 are RED and BLU respectively. Help?

**Comment by wareya** [comment]
"Wrong amount of players while deserializing state" is an uncommon known bug that's been around for a long time. We have no idea what causes it, when it happens, or how to fix it.

**Comment by Medo42** [comment]
This is more of a general bug symtom which says that either the server and client disagree about the number of players present, or that the client consumed the wrong number of bytes in a previous message and is now basically trying to interpret junk data that just LOOKS like the beginning of an update message. Maybe we can add some debugging code to help identify the problem better in cases like this, e.g. by automatically having the client remember the previous 10 commands it received along with the last 1KB of received data.

**Comment by Medo42** [comment]
Continued in #203
