### ISSUE TITLE
Crashing at the start of the game.

### ISSUE THREAD

**Issue by XavGamingX** [Gang-Garrison-2/Gang-Garrison-2#193]
I can't even start the game without it crashing. I tried opening the port, thinking "Maybe it'll work." Nope. It dosn't work. HELP!!

**Comment by Medo42** [comment]
When exactly does the game crash (before or after the "Smoke" splashscreen, the Faucet logo, or even only when trying to join a game), and what exactly happens when it does (Windows error dialog? Game Maker error message? A screenshot is always helpful.)

**Comment by Medo42** [comment]
Closing since we don't have enough info and they had several months to follow up
