### ISSUE TITLE
Spec breaks arena 

### ISSUE THREAD

**Issue by TezalTube** [Gang-Garrison-2/Gang-Garrison-2#196]
If you are the other one in an arena mode game, and the game starts, if you change your team to spectator it will keep the round going and anyone who joins after you can not spawn in until the 20 minute long timer runs out.

**Comment by Medo42** [comment]
Cannot reproduce this. When the game is already running, you shouldn't be able to change teams anymore. If you change to Spectator before the start of the round, the round will not end, but anyone can connect and join one of the empty teams, and this will immediately end the round.

If I overlooked something and this is actually an issue, please open this again provide more detailed instructions for reproducing the problem.
