### ISSUE TITLE
Eliminate all usage of the bbox_ variables

### ISSUE THREAD

**Issue by wareya** [Gang-Garrison-2/Gang-Garrison-2#197]
I recently learned when making http://www.ganggarrison.com/forums/index.php?topic=37927.0 that the bbox_ variables are REALLY FUCKING SLOW, and are rounded to the nearest integer anyway. They probably render to a buffer like when doing collision detection.

**Comment by Medo42** [comment]
"REALLY FUCKING SLOW" appears to be a wild exaggeration. Wareya noticed a certain slowdown in his game, but he was doing in the order of a thousand bbox accesses per frame. Also, the slowdown Wareya saw is not well understood and I couldn't reproduce it in a few tests. So I don't think we should purge every last reference to these variables from the code, but I did some work on reducing them where they are accessed often and where it was easy.
