### ISSUE TITLE
Healing As Medic Drops Frames after rocket jumped

### ISSUE THREAD

**Issue by KevinKuntz255** [Gang-Garrison-2/Gang-Garrison-2#198]
i noticed that after a few games healing as medic will drop your fps to 17 or less, this is annoying because i cannot play with low frames

**Comment by Medo42** [comment]
That sounds weird. Can you provide some more information? Does the issue get worse the more games you play, or does the game suddenly become slow? What is your framerate in this situation in the first game you play? Do you have vsync enabled? Does the framerate only go down when you are actively healing and then go up again?

**Comment by KevinKuntz255** [comment]
Whenever Any Healer begins to heal a teammate and continues, the frames drop down in a slow matter, and when the medic stops the frames go back up to normal, i think the issue does get worse the more i play cause i can't play with really bad ping

**Comment by Medo42** [comment]
I just played a few rounds of GG2 with an eye to CPU load and framerate when healing. Cannot say that I noticed anything though. Also, I don't see where a cumulative effect would happen which makes things worse after playing some rounds.

**Comment by KevinKuntz255** [comment]
well i don't know how this occurs since i don't have any plugins downloaded, just gg2

**Comment by wareya** [comment]
Are you sure it's not a problem with a background program using lots of CPU when you hold down m1? Someone had a similar problem a couple years ago and it turned out to be due to a bad trackpad driver.

**Comment by KevinKuntz255** [comment]
Found out more info about this, it seems that the framedropping happens after you die as med after you ubered while needling in a firefight, atleast after i died like that i started framedropping

**Comment by KevinKuntz255** [comment]
somehow, it seems to happen when certain things happen like being rocket jumped while healing
i

**Comment by Medo42** [comment]
Sorry, still cannot reproduce. Are you sure it's not just a general performance issue? A situation where rockets are flying around and you need to heal a lot tends to be a situation with lots of gibs and blood and particle effects. Try setting particles to "Alternate" or "Off" and also turn off gibs and blood under Options/Engine, and see if that helps.

**Comment by KevinKuntz255** [comment]
i guess it's just me. oh well
