### ISSUE TITLE
Very suspicious code

### ISSUE THREAD

**Issue by PrOF-kk** [Gang-Garrison-2/Gang-Garrison-2#201]
game_init line 241
`//Server respawn time calculator. Converts each second to a frame. (read: multiply by 30 :hehe:)`
`if (global.Server_RespawntimeSec == 0) {`
`global.Server_Respawntime = 1;
`}
 `else
`{
`global.Server_Respawntime = global.Server_RespawntimeSec * 30;
}`

**Comment by Derpduck** [comment]
https://github.com/Medo42/Gang-Garrison-2/blob/master/Source/gg2/Scripts/Game/game_init.gml#L239

**Comment by wareya** [comment]
This isn't suspicious. Variables that exist for multiple frames should not scale with delta time.

There is a bug in the balancer, however.

https://github.com/Medo42/Gang-Garrison-2/blob/2a1d4201592d981dfa58176407e90f4d5bc827c2/Source/gg2/Scripts/Team%20Balance/ServerBalanceTeams.gml#L35

https://github.com/Medo42/Gang-Garrison-2/blob/67432e48abea77b9e7436efac7ae1fb4ef9fec64/Source/gg2/Scripts/GameServer/GameServerBeginStep.gml#L4

Everything else incorporates delta_factor.

**Comment by Medo42** [comment]
How is that suspicious exactly?

Derpduck <notifications@github.com> schrieb am Mi., 10. Jan. 2018, 18:18:

**Comment by PrOF-kk** [comment]
It seemed suspicious for 60 fps gameplay. Anyway thanks for the clarification. Closing.

**Comment by wareya** [comment]
It's good to look for delta time bugs, but make sure to go through the whole chain of events!

We really need to get around to replacing alarms, too.

**Comment by Medo42** [comment]
Blergh, github should scrub fullquotes from reply mails. Anyway, I didn't even pick up on that potential issue when looking at it quickly, so make sure to point out what you see next time.
