### ISSUE TITLE
Querly bubbles go though projectile walls

### ISSUE THREAD

**Issue by PrOF-kk** [Gang-Garrison-2/Gang-Garrison-2#205]
koth_harvest
![Imgur](https://i.imgur.com/ZKlx4Py.png)
gen_destroy
![Imgur](https://i.imgur.com/E28guXn.png)
As you can see it's often possible to get the bubbles stuck inside the projectile walls
![Imgur](https://i.imgur.com/FfwNgEA.png)

**Comment by PrOF-kk** [comment]
Added screenshots, confirmed to not be map-specific, confirmed to happen as client

**Comment by PrOF-kk** [comment]
I believe it's fair to say that this could be part of a bigger collision detection problem, as it's possible to get them stuck in walls
![Imgur](https://i.imgur.com/FD4Ired.png)

**Comment by wareya** [comment]
Yeah the bubble collision code was never very good. It improved a little when I made them slide across steps but it was an emergent improvement instead of an algorithmic one.

**Comment by PrOF-kk** [comment]
Alright, did some testing, the collision is detected the code executed normally, so the issue is almost surely in alarm[0] handling. Unlike collisions with other stuff where it just gets destroyed, with the ProjectileWall it modifies the bubble's speed and lowers alarm[0] by 8. It seems to have been deltatimed correctly... Either way, why do we do that? Why not simply destroy the bubble?

**Comment by PrOF-kk** [comment]
Well, the profiler says that alarm[0] never get triggered, its value goes a lot below 0 and because of this it never gets executed. Weird bug to fix, I guess I'll just check if it's below 0 in the Begin Step and then set it to 1

**Comment by Medo42** [comment]
Does that mean the bubbles actually become immortal by going through such a wall? ;)

**Comment by PrOF-kk** [comment]
They did :). They would have never died of old age after being through a BWall or after reflecting mines
