### ISSUE TITLE
Update 7za.exe distributed with GG2 so that it has the latest security fixes

### ISSUE THREAD

**Issue by Medo42** [Gang-Garrison-2/Gang-Garrison-2#207]
There were several security-relevant issues discovered since the version we bundle with gg2. It's probably not an issue because we control the update.zip file, but still a good idea.

**Comment by PrOF-kk** [comment]
[Agreed](http://www.ganggarrison.com/forums/index.php?topic=37822.0)

**Comment by PrOF-kk** [comment]
Will "fix" this tomorrow, assign to me if you want to
