### ISSUE TITLE
What's with this game.....

### ISSUE THREAD

**Issue by trailmix151** [Gang-Garrison-2/Gang-Garrison-2#21]
For some reason, none of the weapons in my game do damage. I've tried every class and ability but absolutely nothing can damage or even effect the enemy at all. 

I can stab people directly and undeniably in the back as Spy, as well as land a fully charged sniper shot on someone's head with the tracer connecting perfectly but absolutely no damage is done.

I've reinstalled the game 4 times but it still doesn't work.

**Comment by Medo42** [comment]
Old, insufficient information, closing
