### ISSUE TITLE
github feature redirects issue openers to the code contribution guidelines

### ISSUE THREAD

**Issue by wareya** [Gang-Garrison-2/Gang-Garrison-2#210]
![image](https://user-images.githubusercontent.com/585488/36075948-86e6fb70-0f23-11e8-8712-81be00b23511.png)
leads to
https://github.com/Gang-Garrison-2/Gang-Garrison-2/blob/master/Contributing.md

**Comment by Medo42** [comment]
We could add a section there at the start about what we'd like to see in an issue. Or we could rename the Contributing.md so it won't get picked up by that feature (but then it also won't be shown for pull requests). I didn't find a way to disable it selectively just for the issues.

**Comment by Medo42** [comment]
I added a section for issue reporting so the link is at least relevant.
