### ISSUE TITLE
spy stab should short circuit LOS check in some cases

### ISSUE THREAD

**Issue by wareya** [Gang-Garrison-2/Gang-Garrison-2#211]
because of bullet walls

possible short circuits:

- spy hitbox overlapping enemy hitbox
- LOS point overlapping enemy hitbox

**Comment by PrOF-kk** [comment]
I'm working on optimising the StabMask object as you asked. Just to be clear, what do you mean by "LOS point overlapping enemy hitbox"? The various collision_line?

**Comment by Medo42** [comment]
I would actually say that, because the attack is not ranged, it should consider char-solids instead of gun-solids. It feels to me that if the spy could walk to their victim, he should be able to stab them.

**Comment by wareya** [comment]
It still shouldn't go through bulletwalls or team doors.

**Comment by Medo42** [comment]
> It still shouldn't go through bulletwalls (usually) or team doors. Like if there's a real wall in the way.
But if you can walk through it, it's hardly a wall :grin:
