### ISSUE TITLE
not really a game problem but the haxxies dont seem to be working right now

### ISSUE THREAD

**Issue by arctic5** [Gang-Garrison-2/Gang-Garrison-2#215]
title

**Comment by Medo42** [comment]
Is it that time of the year again?

**Comment by Medo42** [comment]
Fixed for now, but I should really have another look at why the service never comes back up after a mariadb upgrade...

**Comment by Medo42** [comment]
I finally removed the systemd unit dependency from faucetauth to mariadb, which seems wrong but will prevent this problem.

**Comment by PrOF-kk** [comment]
Il 26 feb 2018 11:19 PM, "Medo42" <notifications@github.com> ha scritto:
