### ISSUE TITLE
GG2 exe crashes when 5+ mines explode on screen at once (SOUND error)

### ISSUE THREAD

**Issue by ZaSpai** [Gang-Garrison-2/Gang-Garrison-2#224]
Tested on fresh install of GG2 2.9.0

![crash](https://user-images.githubusercontent.com/6680503/38480785-decd0fdc-3c0a-11e8-9854-b374fafd8835.png)

On Windows 8.1

There are occasions where due to the bounds within an object is or isn't drawn, 5 or more mines can explode however the game does not crash as less than 5 have their explosions drawn.

Having a look at the source, given that there's no drawing effects on the new explosion object from what I can tell, is this a sound error? (haven't tested in high intensity environments with other exploding objects like sentry gibs and rockets)

**Comment by wareya** [comment]
see, I said the sound fix wasn't specific to only windows 8.0

**Comment by PrOF-kk** [comment]
Yes this looks like a sound error. Can you test this in 2.8.6 please?

**Comment by PrOF-kk** [comment]
Found the issue, this should be fixed in my next pr

**Comment by ZaSpai** [comment]
@PrOF-kk : Issue didn't exist in 2.8.6 build
Out of interest what's the offending code?

**Comment by wareya** [comment]
https://stackoverflow.com/questions/31072543/reliable-way-to-get-windows-version-from-registry

**Comment by ZaSpai** [comment]
For peeps without the relevant OS, W8.1 has NTKernelVersion of **6.3**

Anyone on W10 check to confirm it's a W8.x exclusive issue?

**Comment by PrOF-kk** [comment]
We already checked it in the beta. I mistakenly believed W8 and W8.1 had the same value
