### ISSUE TITLE
Arena crash on first join

### ISSUE THREAD

**Issue by PrOF-kk** [Gang-Garrison-2/Gang-Garrison-2#240]
**Needs confirmation**
![Imgur](https://i.imgur.com/WbjdQAe.png)

**Comment by Medo42** [comment]
There is no variable called gameStarted in vanilla, however there is one in the aam plugin (Actual Arena Mode).

**Comment by Medo42** [comment]
There is a variable "global.startedGame" in vanilla, but it's unlikely that it will not be defined before use, because it is set in basicRoomSetup and only read in TeamSelectController. I'm closing this and leaving a remark on the gg2f thread of the plugin.

**Comment by PrOF-kk** [comment]
Nice job, given how little info we had
