### ISSUE TITLE
Bubble Step Event: Unknown variable hspeed

### ISSUE THREAD

**Issue by YoshiBleu9427** [Gang-Garrison-2/Gang-Garrison-2#244]
This happened twice in the last two days, so it might actually be a problem in the code rather than just Game Maker being Game Maker.

```ERROR in
action number 1
of  Step Event
for object Bubble:

Error in code at line 2:
   
hspeed += owner.hspeed * 0.2 * global.delta_factor;
                   ^
at position 18: Unknown variable hspeed


```
Happened twice while I was hosting in dedicated mode (and away):
 - yesterday in arena_lumberyard, I don't remember how many players were present
 - today in koth_nucleus, the team selection menu showed only one player was present (in blue team)

Plugins running:
 - Serversent (non required): chat
 - Locally: [arenaOvertimeLimiter](https://www.ganggarrison.com/forums/index.php?topic=38350.0), dynamicRespawnTimes, [FreezeTime](https://www.ganggarrison.com/forums/index.php?topic=32709.0), [serversideAfkCheck](https://www.ganggarrison.com/forums/index.php?topic=38351.0)

**Comment by YoshiBleu9427** [comment]
Looks like the error comes from the serversideAfkCheck plugin, because it would destroy a Character during normal step event. I'm not closing the issue because while it doesn't cause any problems in vanilla, I don't suppose that's by design either.

**Comment by Medo42** [comment]
Interesting find. Apparently the only reason this doesn't happen normally is that in Begin Step, the Bubble checks if it is too far away from the owner. And Game Maker thinks it's a good idea to let distance_to_object return 1000000 if you pass an invalid instance ID.
