### ISSUE TITLE
Taunting input might not work with a 60fps client

### ISSUE THREAD

**Issue by wareya** [Gang-Garrison-2/Gang-Garrison-2#25]
Code to fix:

    if(global.run_virtual_ticks or keyboard_check_pressed(global.taunt))
        ClientInputstate(global.serverSocket, keybyte);

Not the perfect fix, but I don't (and shouldn't) feel like making a separate input message just for taunts.

**Comment by arctic5** [comment]
hi, the same bug exists with the medic call

**Comment by arctic5** [comment]
https://github.com/Medo42/Gang-Garrison-2/commit/78eb36ccefee95de34b62b15418c900316988a4b
bug still occurs with fix

**Comment by wareya** [comment]
30fps or 60fps server?

**Comment by arctic5** [comment]
http://www.ganggarrison.com/forums/index.php?topic=13630.msg1256106#msg1256106

60fps client

**Comment by wareya** [comment]
I can see it breaking with a 30fps server now that I think about it

we need a way to make the taunt and health queue up to the next frame instead of sending an extra input

**Comment by Medo42** [comment]
@arctic5 Are you sure this happened with the taunt key after wareya's fix? The forum discussion is about the medic key, and I know why it happens there (same reason as for the taunt key), but wareya's fix should eliminate that issue.

**Comment by Medo42** [comment]
Never mind, I got it now.
