### ISSUE TITLE
Lack of any kind of API for receiving packets, or appending mod-scale scripts with plugins

### ISSUE THREAD

**Issue by BasedUser** [Gang-Garrison-2/Gang-Garrison-2#251]
To this day, people still have to replace ClientBeginStep to, say, detect when more than one emote is sent per tick. I can think of many more uses for such an API, to detect say, leaving players or player deaths, point captures, etc. (such an api could probably prevent replacing whole swaths of scripts, making many possible plugins compatible with each other again)

**Comment by BasedUser** [comment]
Absolutely!

**Comment by Medo42** [comment]
Can you explain a bit more about that emote chat plugin? I started implementing this but I'm now questioning how useful my approach actually is, so it would be good to understand your plan a bit better.

**Comment by Medo42** [comment]
As far as I remember, we discussed this and the main motivation behind this API was to create a very convoluted data channel for chat. Since the plan is to integrate a chat into vanilla anyway, this won't really be needed.
