### ISSUE TITLE
Ask Github Support to remove "forked" status from this repository

### ISSUE THREAD

**Issue by cspotcode** [Gang-Garrison-2/Gang-Garrison-2#252]
It seems like the "forked from ..." status of this repository causes issues in Github's UI.  Forked repositories are not searchable, and pull requests default to being submitted against Medo42 instead of this organization.

If there is no benefit to keeping the forked status, then Github support can be emailed and asked to de-fork this repository.

**Comment by Medo42** [comment]
Sounds good to me, I guess since my repository that is the "master" one right now it's probably easiest if I ask them.

**Comment by Medo42** [comment]
Sent request to Github support

**Comment by Medo42** [comment]
Fork status is removed. Apparently both repositories act as roots now. There was a bit of confusion in the request in the question of what do do with the other forks, and they ended up remaining forks of my personal repo now... I think I'll ask them to move those over but first let me know what you think please :)

**Comment by cspotcode** [comment]
It sounds like moving the forks to Gang-Garrison-2/Gang-Garrison-2 is going
to be the most useful for the owners of those forks.  I can't think of a
reason someone would be upset by the switch.

**Comment by Medo42** [comment]
On it

**Comment by Medo42** [comment]
And done
