### ISSUE TITLE
Minor Peeve - Graphical - Medic Taunt Length different for RED and BLU

### ISSUE THREAD

**Issue by ZaSpai** [Gang-Garrison-2/Gang-Garrison-2#27]
Not really a bug or anything, just a pet peeve. RED Medic has 11 frames for his (vanilla) taunt while BLU Medic has 12. Iirc the missing frame is either the same or very similar to the first frame of the taunt.
Last checked on the hotfixed GG2.7.2. I haven't looked at season specific sprites or any other alt sprites that edit the taunt.

**Comment by PrOF-kk** [comment]
This has probably been patched, both have 12 frames
![Imgur](https://i.imgur.com/njBtp2n.png)

**Comment by Medo42** [comment]
Indeed, I remember fixing that when working on the gear system.

Looks like it was in 6faea01f9744e982ca17b29945ebab0a24b3f756
