### ISSUE TITLE
Graphical - Minor - KOTH Game Timer Background Not Drawn on Left

### ISSUE THREAD

**Issue by HanakoIkezawa** [Gang-Garrison-2/Gang-Garrison-2#30]
When the timers are set to align left, the background of the timer is not drawn on King of the Hill maps. This affects both stacked and side-by-side setups, but does not affect timers aligned to the center of the screen. Screenshots:

![2014-06-21 01-40-08 hanako s help desk koth_trestle](https://cloud.githubusercontent.com/assets/7866438/3347959/77820c14-f907-11e3-866b-ea8ceeed808b.png)

![2014-06-21 01-40-01 hanako s help desk koth_trestle](https://cloud.githubusercontent.com/assets/7866438/3347960/7b6d6b7a-f907-11e3-82dc-4780c9a552ed.png)

**Comment by Medo42** [comment]
3 1/2 years later...

**Comment by Medo42** [comment]
Fixed by 7b344f05c06ff53ae04ab6016be36b4cd2d3b5e5
