### ISSUE TITLE
Joining a full server with plugins will force you to restart GG2

### ISSUE THREAD

**Issue by nagn** [Gang-Garrison-2/Gang-Garrison-2#31]
This has to do with the fact that we send plugin info in STATE_CLIENT_AUTHENTICATED of serviceJoiningPlayer, while actually dropping players due to the server being full at STATE_EXPECT_NAME, which comes after STATE_CLIENT_AUTHENTICATED. This causes the client to first download plugins and maps, then immediately leave the server due to it being full, forcing a full restart.

We can approach this two ways: dropping the joining player in STATE_CLIENT_AUTHENTICATED before STATE_EXPECT_NAME, or moving the plugin info to STATE_EXPECT_NAME after the server full check. Note that the latter method would break compatibility.

**Comment by wareya** [comment]
hello yes this is still a problem
