### ISSUE TITLE
Gang Garrison 2 Lobby Problem

### ISSUE THREAD

**Issue by MintOre** [Gang-Garrison-2/Gang-Garrison-2#35]
When trying to go to lobby a message appears on screen saying:
Connecting to the lobby server failed
при просмотре базы данных произошла неисправимая ошибка
(while viewing the database unrecoverable error occurred)
What i need to do.
Game not blocked in any of my firewalls.
No internet problems.

**Comment by Medo42** [comment]
I got nothing. Closing because we don't know how to help, please re-open if you have new information.
