### ISSUE TITLE
wareya uncomment this

### ISSUE THREAD

**Issue by arctic5** [Gang-Garrison-2/Gang-Garrison-2#46]
https://github.com/Medo42/Gang-Garrison-2/blob/master/Source/gg2/Objects/Projectiles/StabAnim.events/End%20Step.xml#L22

**Comment by wareya** [comment]
anyone interested in doing this one-liner, it's really boring, I can't motivate myself to bother splitting and committing it :(

**Comment by arctic5** [comment]
just leave it, by now everyones used to visible spy stabs

**Comment by wareya** [comment]
no fuck that
