### ISSUE TITLE
Add missing / additional 2012 Haxxy animations

### ISSUE THREAD

**Issue by hikari-no-yume** [Gang-Garrison-2/Gang-Garrison-2#62]
http://www.ganggarrison.com/forums/index.php?topic=33610.msg1154142#msg1154142

Launchpad Details: [#LP1165596](https://bugs.launchpad.net/bugs/1165596) MedO - 2013-04-07 01:53:36 +0100

**Comment by Medo42** [comment]
The skeletons you find in your closet, long forgotten...
I guess I'll have to do a haxxy weekend where I attack all this old stuff and the new haxxy rewards that still wait for implementation...

**Comment by TazeTSchnitzel** [comment]
There's probably quite a few skeletons in the Haxxy closet.
