### ISSUE TITLE
Notifications of "Player tracking enabled" pop up after death

### ISSUE THREAD

**Issue by TazeTSchnitzel** [Gang-Garrison-2/Gang-Garrison-2#63]
Each time that you die, an annoying notification pops up. Non critical, but annoying to look at.

Launchpad Details: [#LP1165604](https://bugs.launchpad.net/bugs/1165604) Poop Hoop - 2013-04-07 02:18:48 +0100

**Comment by arctic5** [comment]
pretty sure we did as I don't see it happening when i played
