### ISSUE TITLE
Error deleting non-existent sprite

### ISSUE THREAD

**Issue by hikari-no-yume** [Gang-Garrison-2/Gang-Garrison-2#64]
If a person makes a speech bubble right before a map switch, then an error is created something along the lines of:

Error deleting non-existent sprite in object SpeechBubble0.

Launchpad Details: [#LP522449](https://bugs.launchpad.net/bugs/522449) yanjchan - 2010-02-16 03:56:16 +0000

**Comment by Medo42** [comment]
Unable to reproduce the problem, probably outdated
