### ISSUE TITLE
Arena don't want to end

### ISSUE THREAD

**Issue by hikari-no-yume** [Gang-Garrison-2/Gang-Garrison-2#66]
If all the BLU/RED quit after the beginning of the round, arena will sometimes not switch, and the other team is forced to cap the point and wait or wait until a player come in the other team.
It was on 2.2.3, on Normal Gravity Serv.

Launchpad Details: [#LP666260](https://bugs.launchpad.net/bugs/666260) Maruhai - 2010-10-25 13:50:15 +0100

**Comment by Medo42** [comment]
Yep, this is outdated.
