### ISSUE TITLE
Overweight can shoot some bullets through some walls

### ISSUE THREAD

**Issue by hikari-no-yume** [Gang-Garrison-2/Gang-Garrison-2#67]
in certain maps (or maybe all maps) i have noticed the overweight's bullets going through walls or spawn doors.

examples: the no shot walls in arena_harvest can be shot through from some angles. the upper floor of gen_pipeline can be shot through when jumping and shooting down.

happens in latest vinmod and i believe in GG2 as well.

Launchpad Details: [#LP677348](https://bugs.launchpad.net/bugs/677348) baffle-boy - 2010-11-19 06:47:11 +0000

**Comment by PrOF-kk** [comment]
Confirmed in 2.8.6 on koth_harvest
![Imgur](https://i.imgur.com/3vujHLn.png)
