### ISSUE TITLE
koth_harvest-bubbles go through enemy spawn door

### ISSUE THREAD

**Issue by hikari-no-yume** [Gang-Garrison-2/Gang-Garrison-2#69]
Version - gg2 v2.3b16
Server- Washy's Test Server (Unsure if name is correct at this time)

Bug Reporting- During the map koth_harvest, Quote bubbles are able to penetrate into the spawn and does not pop when going through bullet shield wall near the center of the map.
[IMG]http://i1209.photobucket.com/albums/cc392/gg2Vein/screenshot102.png[/IMG]
[IMG]http://i1209.photobucket.com/albums/cc392/gg2Vein/screenshot103.png[/IMG]

To recreate first bug image, place Q/C against spawn door and aim cursor directly ahead and jump repeatedly until bubbles penetrate.

Launchpad Details: [#LP739105](https://bugs.launchpad.net/bugs/739105) gg2Vein - 2011-03-21 02:26:10 +0000

**Comment by PrOF-kk** [comment]
Can confirm that the bubbles go through projectile walls in koth_harvest. They get briefly stuck and then go though. Cannot replicate bubbles going though spawn doors. Using 2.8.6

**Comment by wareya** [comment]
Thanks for confirming that going through spawn doors is outdated. Please open new bug for going through projectile walls.
