### ISSUE TITLE
Firebug flame thrower error

### ISSUE THREAD

**Issue by Rumrusher** [Gang-Garrison-2/Gang-Garrison-2#7]
ERROR in
action number 2
of Other Event: User Defined 2
for object Flamethrower:

Error in code at line 149:

```
                for(i = 0; i < realnumflames; i += 1)
                                  ^
```

at position 37: Unknown variable realnumflames

Is realnumflames a typo or just some Delta_force event?

**Comment by PrOF-kk** [comment]
Fixed a long time ago, close please
