### ISSUE TITLE
autoselect puts me in spectator

### ISSUE THREAD

**Issue by hikari-no-yume** [Gang-Garrison-2/Gang-Garrison-2#73]
Sometimes when I select "autoselect" in the team selection screen I get assigned to the spectators. This happens mostly after a map change and if I press the button quickly. However I don't know if this has an influence because this is the only time and way I'll press the button.

Launchpad Details: [#LP758112](https://bugs.launchpad.net/bugs/758112) Agh - 2011-04-11 22:31:45 +0100

**Comment by Medo42** [comment]
This was fixed in 37e40dd351947ad3129adfd1ca8ec7fe519e78db
