### ISSUE TITLE
in-game music playing in lobby

### ISSUE THREAD

**Issue by hikari-no-yume** [Gang-Garrison-2/Gang-Garrison-2#75]
when you disconnect from the server and return to lobby, the in-game music's still playing (instead of menu music).

Launchpad Details: [#LP767898](https://bugs.launchpad.net/bugs/767898) Elkondo - 2011-04-21 00:50:18 +0100

**Comment by PrOF-kk** [comment]
Tested it, definitely outdated

**Comment by Medo42** [comment]
Oh god it's still from Launchpad.
