### ISSUE TITLE
Data structure with index doesn't exsist for TeamSelectController?

### ISSUE THREAD

**Issue by hikari-no-yume** [Gang-Garrison-2/Gang-Garrison-2#79]
2.3.1
Normal Gravity

I entered this server, however when I did, it gave a error, the wrong number of players derailing state, and that the server was full when it wasn't.

---

ERROR in
action number 1
of  Step Event
for object TeamSelectController:

Data structure with index does not exist.

Launchpad Details: [#LP791786](https://bugs.launchpad.net/bugs/791786) Washy - 2011-06-02 11:39:54 +0100

**Comment by Medo42** [comment]
Another protocol desync bug. Continued in #203.
