### ISSUE TITLE
Killed twice

### ISSUE THREAD

**Issue by TazeTSchnitzel** [Gang-Garrison-2/Gang-Garrison-2#81]
on the kill log, i was killed, then my autogun destroyed, then me again

Launchpad Details: [#LP809566](https://bugs.launchpad.net/bugs/809566) BillyBobJoe - 2011-07-12 22:15:29 +0100

**Comment by arctic5** [comment]
bet you this is just from both the server being inactive and getting rekilled within a short period of time

**Comment by TazeTSchnitzel** [comment]
Doubt it. I think it's a weird bug. But it's from 4 years ago and there's no chance of a response, so let's close it unless it comes up again.
