### ISSUE TITLE
Changing class in arena before round starts prevents player from playing that round

### ISSUE THREAD

**Issue by TazeTSchnitzel** [Gang-Garrison-2/Gang-Garrison-2#85]
If a player changes class right after the "round begins in X seconds" message finishes and the actual round begins, the player will be "dead" and cost his team a player.

Not too sure if I accurately described the problem, but it's mostly an annoyance.

Launchpad Details: [#LP893857](https://bugs.launchpad.net/bugs/893857) AstronautGuy - 2011-11-23 04:17:33 +0000

**Comment by arctic5** [comment]
well i mean you technically are considered dead after the game started sooooooo
