### ISSUE TITLE
Version 2.4.1 Crash when launching server, cant find online servers

### ISSUE THREAD

**Issue by hikari-no-yume** [Gang-Garrison-2/Gang-Garrison-2#86]
---

ERROR in
action number 1
of End Step Event
for object PlayerControl:

Error in code at line 1:
   if(global.myself.object == -1) exit;
                   ^
at position 18: Unknown variable object

---

ERROR in
action number 1
of End Step Event
for object Spectator:

Error in code at line 1:
   if(global.myself.object != -1)
                   ^
at position 18: Unknown variable object

---

ERROR in
action number 1
of Draw Event
for object ScorePanel:

Error in code at line 45:
       if global.myself.object==-1{
                        ^
at position 23: Unknown variable object

Launchpad Details: [#LP897170](https://bugs.launchpad.net/bugs/897170) Vlad Tonyaev - 2011-11-28 11:11:20 +0000

**Comment by Medo42** [comment]
old, insufficient info, closing
