### ISSUE TITLE
Crash/Freeze Upon Closing

### ISSUE THREAD

**Issue by hikari-no-yume** [Gang-Garrison-2/Gang-Garrison-2#88]
Basically as in summary. When I close the game, the screen goes black and the computer becomes completely unresponsive. Even the numlock doesn't function. CTRL-ALT-DEL doesn't do anything; ALT-F4 doesn't do anything; I have to hard-reboot the computer to get it to work. This problem also occurs following an error that approximately says 'wrong data sent' (or received, I don't have much time to read it) or something, when loading a new map while connected to a server.

The server was 'Mew's (something-or-other)', one of the seven that I can see from my machine. (there aren't really only seven servers, are there?)

Apologies, but I don't have any way of getting a screenshot due to the nature of the bug.

Obviously, I would appreciate it if this could be explained and/or fixed.

Thanks in advance,
semininja

Launchpad Details: [#LP903528](https://bugs.launchpad.net/bugs/903528) N Hedler - 2011-12-13 03:24:25 +0000

**Comment by Medo42** [comment]
Closing because it's outdated and must be an OS level issue, and wishing myself back to a time when 7 servers was considered "few".
