### ISSUE TITLE
wrong disconnect message w. full server/custom maps

### ISSUE THREAD

**Issue by hikari-no-yume** [Gang-Garrison-2/Gang-Garrison-2#89]
If a server is full and is currently running a custom map (that you must download) and you try to connect the client will start downloading that map and during the download process you get a message saying "server disconnected".

I think the correct behaviour is to never start downloading the map at all and just get a "server is full" message.

Launchpad Details: [#LP909676](https://bugs.launchpad.net/bugs/909676) Orson Peters - 2011-12-29 11:26:18 +0000

**Comment by PrOF-kk** [comment]
Commit 4ac496068a48489550c3b8b9a22718a29d2cf182 also fixes this

**Comment by Medo42** [comment]
No, it doesn't. I'd have to check if it's still an issue anyway but I think it is.
