### ISSUE TITLE
Client crashes on map loading randomly

### ISSUE THREAD

**Issue by hikari-no-yume** [Gang-Garrison-2/Gang-Garrison-2#91]
When changing map, suddenly the game freezes and the message "The server has sent invalid data" followed by a game crash appears.

It is not map-specific, but apparently only happens on custom maps, and usually/only (?confirmation?) after downloading/updating one.
When the error appears, the map is visible in the background, but no players, and the error appears immediately.

The map and the lack of a "Invalid number of players while deserializing" make me think this happens in the second part of FULL_UPDATE, after the map change, but before a normal state update.

When restarting after the crash and joining the server, it usually works without any problem, so the map was downloaded completely enough for the md5.

I haven't met the bug often lately, but on the other hand, I rarely anymore have to download maps, so maybe the two really are related.

Name of version: 2.4 and onwards
Name of server: many different servers, this is probably irrelevant.
Instructions to reproduce: Play a lot. No seriously, I have no idea, beyond maybe try to download lots of extra maps via game. And even that gives an error once every 15 times or so.
A Screenshot: Probably useless.

Launchpad Details: [#LP922782](https://bugs.launchpad.net/bugs/922782) Orpheon - 2012-01-27 19:41:13 +0000

**Comment by Medo42** [comment]
Closed because it's probably outdated and sounds like a general protocol error (i.e. see #203)
