### ISSUE TITLE
Medic? bug on mapswitch

### ISSUE THREAD

**Issue by hikari-no-yume** [Gang-Garrison-2/Gang-Garrison-2#93]
---

ERROR in
action number 1
of Begin Step Event
for object Client:

In script ClientBeginStep:
In script doEventPlayerDeath:
Error in code at line 42:
       if (victim.object.currentWeapon.object_index == Medigun)
                         ^
at position 24: Unknown variable currentWeapon

Happened immediately after downloading a new map on mapswitch.  The server was vanilla as far as I can tell.  Caused me to crash, but along with it came a "Server sent unexpected data" error, so I am not sure which one truly triggered the crash or if the two go hand in hand.

Launchpad Details: [#LP1005417](https://bugs.launchpad.net/bugs/1005417) John Lopez - 2012-05-28 08:00:19 +0100

**Comment by Medo42** [comment]
Probably protocol desync related. Continued in #203
