### ISSUE TITLE
Killcam not working

### ISSUE THREAD

**Issue by TazeTSchnitzel** [Gang-Garrison-2/Gang-Garrison-2#96]
This might be a one-off problem that vanishes with a reboot, but when testing for a different fix I noticed that the killcam didn't work. The code in DeathCam Alarm 0 "errors out" in screen_save_part(tempfile,0,0,800,600);

Due to the way Game Maker handles errors, this simply aborts the rest of the event execution without showing a message, and the killcam silently fails to show.

GG2 version: commit#e2719b57cad6ab4846779aeebb13fd98bd9b0119

Launchpad Details: [#LP1049121](https://bugs.launchpad.net/bugs/1049121) MedO - 2012-09-11 14:43:23 +0100

**Comment by arctic5** [comment]
if its a game maker error there is nothing we can do about it anyways

**Comment by TazeTSchnitzel** [comment]
Well, it's still an issue. Not one we can do much about, but an issue nonetheless.

**Comment by wareya** [comment]
"speed of light too slow for rational interstellar travel"

**Comment by Medo42** [comment]
Just because it's not a bug in our code doesn't mean we couldn't work around it in some way.

In other news:
"I don't even care anymore"
-- Medo
